<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEYDdg6q\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEYDdg6q/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerEYDdg6q.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerEYDdg6q\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerEYDdg6q\App_KernelTestDebugContainer([
    'container.build_hash' => 'EYDdg6q',
    'container.build_id' => 'e4226589',
    'container.build_time' => 1669126593,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEYDdg6q');
